version: '3'
services:
  web:
    container_name: django-docker
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /code
    ports:
      - 8000:8000
    volumes:
      - .:/code
      - ./media:/code/media
    depends_on:
      db:
        condition: service_healthy
  
  db:
    container_name: django-docker-db
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: django_docker
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      MYSQL_ALLOW_ENPTY_PASSWORD: 'yes'
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 33306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "django", "-pmysql"]
