# Generated by Django 4.2 on 2024-08-05 03:30

from django.db import migrations, models
import file_downloader.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='subdirectory',
            field=models.CharField(default='default_subdirectory', max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=file_downloader.models.upload_to_dynamic_subdirectory),
        ),
    ]
