# Generated by Django 4.2 on 2024-08-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_downloader', '0002_uploadedfile_subdirectory_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='subdirectory',
            field=models.CharField(default='Output', max_length=255),
        ),
    ]
